version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"  # Root directory, assuming the submodules are directly under the root
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-name: "subfolder1"
      - dependency-name: "subfolder2"
