# Specify locations of manifest files for each package manager using `directories`

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/subfolder1"
      - "/subfolder2"
    schedule:
      interval: "weekly"
